### ISSUE TITLE
nomodule scared.config.helpers

### ISSUE THREAD

**Issue by Noumanijaz744** [CPJKU/cpjku_dcase22#4]
Traceback (most recent call last):
  File "/data/nouman/.conda/envs/dcase22_t1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/nouman/.conda/envs/dcase22_t1/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/nouman/cpjku_dcase22/experiments/dcase22/t1/teachers_gang.py", line 13, in <module>
    from experiments.dcase22.t1.config_updates import add_configs
  File "/data/nouman/cpjku_dcase22/experiments/dcase22/t1/config_updates.py", line 2, in <module>
    from sacred.config_helpers import DynamicIngredient, CMD
ModuleNotFoundError: No module named 'sacred.config_helpers'

while reproducing this code i am facing this error .please reply how to solve it

**Comment by fschmid56** [comment]
Did you install sacred with the provided command?
`pip install -e 'git+https://github.com/kkoutini/sacred@v0.0.1#egg=sacred' `

If you clone the repo from [here](https://github.com/kkoutini/sacred) and install it, then you might end up using the wrong version of sacred. This repo relies on the sacred modification in the branch called _ba3l_.
